{{- /*
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if eq .Values.controller.enable true }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "controller.fullname" . }}
  labels:
    {{- include "controller.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: main
    port: {{ .Values.controller.service.port }}
    protocol: TCP
    targetPort: main
  - name: internal
    port: {{ .Values.controller.service.internalport }}
    protocol: TCP
    targetPort: internal
  publishNotReadyAddresses: true
  selector:
    {{- include "controller.selectorLabels" . | nindent 4 }}
{{- end }}